name: Docker Build and Push

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch.


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Stored in GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Stored in GitHub secrets
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile  # Path to your Dockerfile
        tags: skppy/myapi:latest
        push: true  # Pushes the image to Docker Hub